In [1]:
import pandas as pd
import os
import numpy as np
import pickle
#from optparse import OptionParser # use later  

In [2]:
channels=['ch0','ch1','ch2','ch3','ch8','ch9','ch10','ch11']
data_dict={}

In [3]:
filelist = []
dirname = '/home/furkan/work/flicanalyzer/waveform/2019-12-14_18-05-55'
i=0
for filename in os.listdir(dirname):
    if '.dat' in filename:
        print(dirname+'/'+filename)
        filelist.append(dirname+'/'+filename)
        
        fil=pd.concat([pd.read_csv(item, names=[item[:-4]]) for item in filelist], axis=1)
        x = pd.DataFrame(fil).to_numpy()
        print(x)    
        s=np.transpose(x)
        print(s.shape)
        Nevent=int(s.size/2024)

        arr=s.reshape(Nevent,2024)

        signal=np.delete(arr, np.s_[0:24], axis=1) 

        data_dict.update({channels[i] : signal})
        i+= 1
        
        filelist=[]        

output = open('myfile.pkl', 'wb')
pickle.dump(data_dict, output)
output.close()
    

/home/furkan/work/flicanalyzer/waveform/2019-12-14_18-05-55/Cosmic_Vertical_VBias47V_Ch8-2019-12-14_18-05-55.dat
[[43690]
 [43690]
 [ 1012]
 ...
 [ 1537]
 [ 1542]
 [ 1531]]
(1, 25300000)
/home/furkan/work/flicanalyzer/waveform/2019-12-14_18-05-55/Cosmic_Vertical_VBias47V_Ch3-2019-12-14_18-05-55.dat
[[43690]
 [43690]
 [ 1012]
 ...
 [ 1522]
 [ 1523]
 [ 1521]]
(1, 25300000)
/home/furkan/work/flicanalyzer/waveform/2019-12-14_18-05-55/Cosmic_Vertical_VBias47V_Ch1-2019-12-14_18-05-55.dat
[[43690]
 [43690]
 [ 1012]
 ...
 [ 1520]
 [ 1515]
 [ 1513]]
(1, 25300000)
/home/furkan/work/flicanalyzer/waveform/2019-12-14_18-05-55/Cosmic_Vertical_VBias47V_Ch9-2019-12-14_18-05-55.dat
[[43690]
 [43690]
 [ 1012]
 ...
 [ 1541]
 [ 1536]
 [ 1538]]
(1, 25300000)
/home/furkan/work/flicanalyzer/waveform/2019-12-14_18-05-55/Cosmic_Vertical_VBias47V_Ch0-2019-12-14_18-05-55.dat
[[43690]
 [43690]
 [ 1012]
 ...
 [ 1526]
 [ 1529]
 [ 1529]]
(1, 25300000)
/home/furkan/work/flicanalyzer/waveform/2019-12-14_18-05-55/Cosmi

In [4]:
pkl_file = open('myfile.pkl', 'rb')
mydict2 = pickle.load(pkl_file)
pkl_file.close()


In [5]:
mydict2

{'ch0': array([[1535, 1541, 1545, ..., 1548, 1551, 1545],
        [1534, 1539, 1538, ..., 1526, 1540, 1535],
        [1534, 1537, 1539, ..., 1499, 1492, 1495],
        ...,
        [1536, 1534, 1533, ..., 1539, 1539, 1535],
        [1534, 1537, 1532, ..., 1532, 1540, 1537],
        [1536, 1537, 1542, ..., 1537, 1542, 1531]]),
 'ch1': array([[1533, 1535, 1535, ..., 1511, 1515, 1515],
        [1533, 1536, 1535, ..., 1532, 1533, 1533],
        [1534, 1533, 1539, ..., 1271, 1267, 1259],
        ...,
        [1535, 1534, 1536, ..., 1534, 1532, 1531],
        [1529, 1539, 1531, ..., 1524, 1529, 1533],
        [1537, 1538, 1536, ..., 1522, 1523, 1521]]),
 'ch2': array([[1525, 1517, 1520, ..., 1539, 1544, 1534],
        [1531, 1525, 1521, ..., 1518, 1521, 1519],
        [1519, 1526, 1516, ..., 1419, 1430, 1431],
        ...,
        [1529, 1519, 1517, ..., 1525, 1520, 1519],
        [1530, 1522, 1522, ..., 1500, 1503, 1510],
        [1524, 1519, 1521, ..., 1520, 1515, 1513]]),
 'ch3': array([[